### ISSUE TITLE
Design ETL pipeline

### ISSUE THREAD

**Issue by ambergman** [edgi-govdata-archiving/filtration#1]
What do we need from the incoming data?

**Comment by DSLituiev** [comment]
We need to build a pipeline that takes difference set from page freezer so that further we can produce categorization of text chunks.

**Comment by aschn** [comment]
step 0: incoming data format (issue TODO)
step 1: naive deduplication (issue #6)
step 2: create separate pipeline from image changes (issue TODO)
step 3: feature extraction (issue #4)
step 4: clustering (issue TODO)
step 5: score cluster quality (issue TODO)
step 6: rank clusters on importance (issue #7)
step 7: output (issue TODO)

**Comment by dcwalk** [comment]
This issue was moved to edgi-govdata-archiving/web-monitoring-processing#9
