### ISSUE TITLE
Feature Extraction [3]

### ISSUE THREAD

**Issue by abelsouza** [edgi-govdata-archiving/filtration#4]
- Tokenization;
-- HTML Tags (Eg., **\<head>, \<body>, \<tr>\/\<td>**);
- TF + IDF;
-- Term frequency - raw frequency per term;
-- Inverse document frequency - term is common or rare across all documents;
--- E.g.: _Logarithmically scaled inverse fraction of the documents that contain the word, obtained by dividing the total number of documents by the number of documents containing the term, and then taking the logarithm of that quotient_;
- Analyst Feedback;
-- Domain specialist

**Comment by dcwalk** [comment]
This issue was moved to edgi-govdata-archiving/web-monitoring-processing#12
