### ISSUE TITLE
Data ingestion [step 0]

### ISSUE THREAD

**Issue by nadesai** [edgi-govdata-archiving/filtration#5]
For each subdomain, need to ingest:
- source diff (raw HTML changes)
- bytes added
- bytes removed
- enclosing HTML tag
- context (HTML page source before/after). (Open question here - how much context is sufficient? Would a page "summary" do, or just the enclosing paragraph, instead of the full page source?)
- time diff is recorded (may not be relevant due to noise in when pages are scraped)
- Analyst feedback/annotations

**Comment by dcwalk** [comment]
This issue was moved to edgi-govdata-archiving/web-monitoring-processing#13
