### ISSUE TITLE
Rank change clusters based on TF/IDF and analyst feedback

### ISSUE THREAD

**Issue by aleatha** [edgi-govdata-archiving/filtration#7]
Once changes have been clustered, they should be ranked to allow the analyst to prioritize which changes to examine first.

Ranks are calculated by:
- calculating the k most representative words from each cluster (for example, by using entropy gain)
- weighting the words using a combination of TF/IDF and analyst feedback weights.

**Comment by dcwalk** [comment]
This issue was moved to edgi-govdata-archiving/web-monitoring-processing#15
