### ISSUE TITLE
Score Cluster Quality [5]

### ISSUE THREAD

**Issue by vidkum1** [edgi-govdata-archiving/filtration#8]
Doing  a grid search for the optimum number of clusters and clustering method (e.g. Kmeans Pam etc) based on cluster quality. We could use something like a similarity score to determine how similar the points are within the clusters.

**Comment by dcwalk** [comment]
This issue was moved to edgi-govdata-archiving/web-monitoring-processing#16

**Comment by dcwalk** [comment]
This issue was moved to edgi-govdata-archiving/web-monitoring-processing#17
